#!/usr/bin/env bash

# Инструкции по захостованию на Railway

echo "🚀 Valentine Game - Railway Deployment Guide"
echo ""
echo "📋 Шаг 1: Подготовка репозитория"
echo "  1.1 Убедитесь, что код закоммичен в GitHub"
echo "  1.2 Проверьте наличие всех файлов:"
echo "      - package.json"
echo "      - Procfile"
echo "      - server.js"
echo "      - frontend/"
echo ""

echo "🔐 Шаг 2: Создание Project на Railway"
echo "  2.1 Откройте railway.app"
echo "  2.2 Нажмите 'New Project'"
echo "  2.3 Выберите 'Deploy from GitHub'"
echo "  2.4 Подключите аккаунт GitHub"
echo "  2.5 Выберите репозиторий"
echo ""

echo "📦 Шаг 3: Добавление PostgreSQL плагина"
echo "  3.1 В проекте Railway нажмите '+ New'"
echo "  3.2 Выберите 'PostgreSQL'"
echo "  3.3 Railway автоматически создаст переменные окружения"
echo ""

echo "🔑 Шаг 4: Добавление переменных окружения"
echo "  4.1 Нажмите на веб-приложение"
echo "  4.2 Перейдите на вкладку 'Variables'"
echo "  4.3 Добавьте:"
echo ""
echo "Telegram:"
echo "  TELEGRAM_BOT_TOKEN=8294908477:AAGdjRo5ucowozIT81qGmMJ5vP8R0YAYDNM"
echo "  TELEGRAM_BOT_USERNAME=valentinmvbot"
echo ""
echo "Cloudinary:"
echo "  CLOUDINARY_CLOUD_NAME=dvzwzytog"
echo "  CLOUDINARY_API_KEY=396524255276334"
echo "  CLOUDINARY_API_SECRET=7XHmrXMN2ZfcIZcJW58o0wINd68"
echo ""
echo "Приложение:"
echo "  NODE_ENV=production"
echo "  APP_URL=<скопируйте URL из Railway>"
echo ""

echo "✅ Шаг 5: Проверка Deployment"
echo "  5.1 Railway автоматически запустит build"
echo "  5.2 Проверьте логи в 'Deployment' секции"
echo "  5.3 После успеха нажмите на публичный URL"
echo ""

echo "🎮 Готово! Приложение запущено на Railway 🚀"
